default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dating_sim_dev
  # username: <%= ENV["POSTGRES_DEV_USER"] %>
  # password: <%= ENV["POSTGRES_DEV_PASSWORD"] %>
  # host: <%= ENV["POSTGRES_DEV_HOST"] %>
  # port: <%= ENV["POSTGRES_DEV_PORT"] %>

test:
  <<: *default
  # host: postgres
  database: dating_sim_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # database: <%= ENV["POSTGRES_PROD_DB"] %>
  # username: <%= ENV["POSTGRES_PROD_USER"] %>
  # password: <%= ENV["POSTGRES_PROD_PASSWORD"] %>
  # host: <%= ENV["POSTGRES_PROD_HOST"] %>
  # port: <%= ENV["POSTGRES_PROD_PORT"] %>
